# Setup the devcontainer with volumes for cache and node_modules, and XDG_CACHE_HOME. Running `pnpm` inside a container
# without this setup hits weird errors.

services:
  devcontainer:
    build: .
    pull_policy: missing
    command: sleep infinity
    environment:
      - XDG_CACHE_HOME=/root/.cache
    volumes:
      - source: ..
        target: /workspace
        type: bind
      - source: cache
        target: /root/.cache
        type: volume
      - source: node_modules
        target: /workspace/node_modules
        type: volume

volumes:
  cache: {}
  node_modules: {}
